from most_frequent_kmers import frequency_table
from substring_matching import strip_list
from tqdm import tqdm

def find_clumps(seq, k, l, t):
    patterns = []
    seq = list(seq)
    n = len(seq)

    for i in tqdm(range(n-l)):
        window = seq[i:i+l]
        freq_map = frequency_table("".join(window), k)

        for pattern in list(freq_map.keys()):
            if freq_map[pattern] >= t:
                patterns.append(pattern)
    return list(set(patterns))

if __name__ == "__main__":
    genome = "GTAGGCCTTACCGTTCACTATCCGTATGGTCACCAAGGCCGGTTACAGCGTTGTGACTACAACTTACCTCTCGGTGAGATCGTACATAAAAAATGGTAGCTACTGGTCAAAGGCTGGTCCAGAAGATTAACCAGAAGATCAGAAGATTAGCCCAGATGAAATCGGCACAGTCGAGTTGACCCGGAGCCCGAAGGGTTTGAATGCAATTAGCTAGCATCAATCGAAACGTTTCAGTGGAGGTTGGTCTCGCAGCCCGTCGCCTTGTCGGTTCGTTTACTTACCGAGGGGGGGCCGGTGCCGGTGGGCCGGTAGTGATACTCTTCCTTGTAGTAATAGGGTACCCATCTGAGCCCTCAATAGTCACATTAATATTCCCAAATAGGATCGGGGGGCCGTAACTCCGATATACTAAGAGCAGTCGGCGACTCCCCGAGCGGCGAGCGGCGCGGCGCAGCGGCTCCGCTGAAATCATCATGTATAATCATGTAATGTACCGTCCATCGGACTCTACCAACCAAGATACCTGATCTGTCAAGCCTGCTCCGATCACCCGCCCTGCAGACGGAAAGCAGAGTACGGATTAAAGAGTGGGATCCTCATCTATACTATTGCTTCAGGCTAAGCCTTAAAACTAGAAGGCAAACTAAGAGATGCAGTACGCGGAGCGTTAGTAGTAGTTTGCTTAGACACTGAGGACACTGGCATTGTGGGCATGGGCACCCACCGCACCAATAGTCTGCCAGATAAGACAAACTGGCAACACACCCGGGGCTTGCTTCCATGGCCCGGGGTATCTTGATAGGAGGGCGCCCGTTACGATCACGCCGAGTTTAATCGGTTTACTATTTAAAGTACATTGATAGTGCACGATTTAACTACGCTCTTATTGAGTTCTGCGTTTCGTTTGGGTCGGGAGTGTATATCCGAGCCCATCCGTCCTAACCCGGTTCCATCCTCCTATCACGATAAGTTCGACACCCACCGGGACTTGATCCATCGCTGTTGGTTACGCTAGTAGGCACGAAGTACTTCAGTATGGAGCGAAACTCGTATAGCGTATAATTGCACTCTCCGGATCCGGCGCGCACCCACTGCAATGGCTATGTTATAGTATAACATCGGATAAACTGACAGTGCGGGTCTTACACTTTCAATGCATTTGAAAGTTCACCTCGGGCTTCGGGCCCAAATTCAAATGGTGGGACTGAAGCAACGACACCTGAGGACGACAGGCATGCGCGTAGCAGTATACCCATTTGGCCACGTCACACCGGCGATCTCATGTCCATGTGTCCCACATGTGCATGTGTCTCTCTTGGGGACATTTCTAATTCCGCGCCTGGCGGGCCGTGGAGACCGCTACCCTTGCGGTGTGGGTTGAATGCAGCCCCTCTGTAATAAGAGATACATCAATGAACGCTCCGTTCCTGGGACTTGACCTGGGACTAGCCAGAGCACCAGAGCACGCACCACGTAAACTCTGACCCACGTACGAGTGTCTTCGTATGTTAACTTTGGTTGGCCTCTCTAGAGGTTGCCCCCTGCTCTATCTTCTTAAGAGGTTATAATGTGAGAGGCTTATATAGCTTTTGTCACCTACGGGAACGCTCACGAGACGCAGGTCGACCACGCCCTTTGACTCGGGATCGCGTCTTCAAGAAGGCTCGCGACACTTAGCCGTGCGTATGCGCCTCAGTGC"
    k = 8
    l = 28
    t = 4
    print(strip_list(str(find_clumps(genome, k, l, t))))